/* Optional real-browser suite. Requires approved local Playwright tooling and a Chromium installation.
 * All application APIs are explicit in-memory fixtures; this does not certify live Frappe/provider behavior.
 */
'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '../..');
const output = path.join(root, 'dev/screenshots');
const port = Number(process.env.PREVIEW_PORT || 8791);
const base = 'http://127.0.0.1:' + port;
const server = spawn(process.execPath, [path.join(root, 'dev/preview-server.cjs')], { env: { ...process.env, PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
const ready = new Promise((resolve, reject) => { server.stdout.on('data', (chunk) => { if (String(chunk).includes('Mock Intelligence preview:')) resolve(); }); server.on('error', reject); server.on('exit', (code) => { if (code) reject(new Error('Preview server failed: ' + code)); }); });
let browser;
(async () => {
  await ready; fs.mkdirSync(output, { recursive: true });
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1040 }, deviceScaleFactor: 1, reducedMotion: 'reduce' });
  const page = await context.newPage(), errors = [], outbound = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.route('**/*', async (route) => { if (!route.request().url().startsWith(base)) { outbound.push(route.request().url()); await route.abort(); } else await route.continue(); });
  const screenshot = (name) => page.screenshot({ path: path.join(output, name + '.png'), fullPage: true });
  const waitApp = async () => { await page.waitForSelector('.fi-welcome'); await page.waitForFunction(() => !document.querySelector('.fi-app').getAttribute('aria-busy') || document.querySelector('.fi-app').getAttribute('aria-busy') === 'false'); };
  await page.goto(base + '/?scene=empty'); await waitApp();
  assert.equal(await page.locator('.fi-starters [data-action="starter"]').count(), 4, 'the welcome screen offers its starters');
  assert.ok(await page.evaluate(() => preview.calls.some((row) => row.method === 'list_conversations')), 'the app still fetches its conversations on boot');
  await screenshot('workspace-empty-desktop');
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="approve"]');
  await page.locator('.fi-approval').scrollIntoViewIfNeeded(); await screenshot('workspace-approval-desktop');
  await page.locator('#theme-toggle').click(); await screenshot('workspace-approval-dark');
  await page.locator('[data-action="approve"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="messages"]').textContent.includes('Review complete')); /* the answer in the thread is the outcome; no Completed chip */
  assert.equal(await page.evaluate(() => preview.calls.filter((row) => row.method === 'approve').length), 1);
  await page.locator('[data-action="rename-title"]').click(); await page.locator('.fi-title-input').fill('Reviewed open orders'); await page.locator('.fi-title-input').press('Enter');
  await page.waitForFunction(() => document.querySelector('[data-slot="title"]').textContent === 'Reviewed open orders');
  await page.locator('[data-action="archive"]').click(); await page.locator('[data-action="confirm-archive"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="subtitle"]').textContent.includes('Archived'));
  assert.equal(await page.locator('.fi-composer textarea').isDisabled(), true);
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="deny"]'); await page.locator('[data-action="deny"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="messages"]').textContent.includes('The request was denied'));
  assert.equal(await page.evaluate(() => preview.calls.find((row) => row.method === 'approve').args.decision), 'deny');
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="conversation"]');
  await page.locator('[data-action="conversation"]').click();
  const scoped = await page.evaluate(() => preview.calls.filter((row) => row.method === 'approve').pop());
  assert.equal(scoped.args.decision, 'always', 'For this conversation maps to a scoped always');
  assert.equal(scoped.args.scope, 'This Conversation');
  await page.waitForFunction(() => document.querySelector('[data-slot="banner"]').textContent.includes('will not ask again in this conversation'));
  await page.goto(base + '/?scene=bulk'); await page.waitForSelector('.fi-approval-bulk'); /* the scene deep-links into chat-1 natively */
  assert.equal(await page.locator('.fi-approval').count(), 1, 'three pending actions collapse into one grouped card');
  assert.equal(await page.locator('.fi-bulk-row').count(), 3);
  assert.ok((await page.locator('.fi-approval-bulk h3').textContent()).includes('3 actions'));
  assert.equal(await page.locator('[data-input="bulk-remember"]').isChecked(), false, 'remember starts unchecked');
  await screenshot('approval-bulk-desktop');
  await page.locator('[data-action="approve-all"]').click();
  const bulkCall = await page.evaluate(() => preview.calls.find((row) => row.method === 'decide_approvals'));
  assert.deepEqual(JSON.parse(bulkCall.args.names), ['approval-b1', 'approval-b2', 'approval-b3']);
  assert.equal(bulkCall.args.decision, 'approve', 'unchecked bulk approve stays one-off');
  assert.ok(!('scope' in bulkCall.args), 'one-off bulk sends no scope');
  await page.waitForFunction(() => document.querySelector('[data-slot="messages"]').textContent.includes('Review complete'));
  await page.goto(base + '/?scene=auto'); await page.waitForSelector('.fi-tool-group');
  await page.locator('.fi-tool-group-head').click();
  assert.equal(await page.locator('.fi-tool-auto').count(), 1, 'the policy-decided step renders as a sealed row');
  assert.ok((await page.locator('.fi-tool-auto .fi-tool-tag').textContent()).includes('Auto-approved by policy'));
  await screenshot('auto-approved-row');
  await page.goto(base + '/?scene=tools'); await page.waitForSelector('.fi-tool-group');
  assert.equal(await page.locator('.fi-tool-group').count(), 1, 'consecutive tool steps collapse into one card');
  assert.equal(await page.locator('.fi-approval').count(), 0, 'no standalone tool cards remain');
  const groupHead = page.locator('.fi-tool-group-head');
  assert.ok((await groupHead.textContent()).includes('Used 5 tools'));
  assert.equal(await groupHead.getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('.fi-tool-group-body').isVisible(), false);
  await screenshot('tool-group-collapsed');
  await groupHead.click();
  assert.equal(await groupHead.getAttribute('aria-expanded'), 'true');
  assert.equal(await page.locator('.fi-tool-group .fi-tool-row').count(), 5);
  const rowsText = (await page.locator('.fi-tool-group .fi-tool-row').allTextContents()).join(' ');
  assert.ok(rowsText.includes('Searching Supplier records') && rowsText.includes("Reading Supplier 'Acme Corp'"), 'rows use gerund labels');
  assert.ok(rowsText.includes('invoice-acme.pdf'), 'file actions name the attachment');
  assert.ok(!rowsText.includes('file-9d580'), 'raw File IDs never surface in the visible rows');
  assert.equal(await page.locator('.fi-file-ref').evaluate((node) => node.tagName), 'SPAN', 'file chips are plain labels, not links');
  const firstRow = page.locator('.fi-tool-group .fi-tool-row').first();
  await firstRow.click();
  assert.equal(await firstRow.getAttribute('aria-expanded'), 'true', 'row toggles its detail');
  assert.equal(await page.locator('.fi-tool-group .fi-tool-block').first().locator('.fi-tool-detail').isVisible(), true, 'args detail expands in place');
  await screenshot('tool-group-expanded');
  await page.waitForFunction(() => { const thread = document.querySelector('.fi-thread'); return thread.scrollHeight > thread.clientHeight; });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false, 'no horizontal page scroll');
  await page.evaluate(() => { const thread = document.querySelector('.fi-thread'); thread.scrollTop = 0; thread.dispatchEvent(new Event('scroll')); });
  await page.waitForSelector('.fi-scroll-bottom:not([hidden])');
  await screenshot('scroll-to-bottom');
  await page.locator('.fi-scroll-bottom').click();
  await page.waitForFunction(() => { const thread = document.querySelector('.fi-thread'); return thread.scrollHeight - thread.scrollTop - thread.clientHeight < 160; });
  await page.waitForFunction(() => document.querySelector('.fi-scroll-bottom').hidden);
  await page.goto(base + '/?scene=empty'); await waitApp();
  await page.locator('[data-action="new"]').click();
  const modelButton = page.locator('[data-picker-btn="model"]');
  assert.ok((await modelButton.textContent()).includes('gpt-4.1'), 'model picker shows the provider default');
  await modelButton.click();
  assert.equal(await page.locator('[data-picker-menu="model"]').isVisible(), true, 'menu opens');
  assert.equal(await page.locator('[data-picker="model"] [data-picker-option]').count(), 3, 'catalog models listed');
  assert.equal(await page.locator('[data-picker="model"] [data-picker-option]').first().getAttribute('aria-selected'), 'true', 'default model checked');
  assert.equal(await page.locator('[data-picker-search="model"]').count(), 0, 'short catalogs skip the search box');
  await page.locator('[data-picker="model"] [data-picker-option]').nth(2).click();
  assert.ok((await modelButton.textContent()).includes('gpt-4o'));
  await screenshot('composer-model-picked');
  await page.locator('.fi-composer textarea').fill('Summarize the fictional preview fixtures.');
  await page.locator('.fi-send').click();
  await page.waitForSelector('[data-action="approve"]');
  const modelSend = await page.evaluate(() => preview.calls.find((row) => row.method === 'send_message'));
  assert.equal(modelSend.args.model, 'gpt-4o', 'a custom model choice rides with the first message');
  await page.goto(base + '/?scene=empty'); await waitApp();
  await page.locator('[data-action="new"]').click();
  await page.locator('.fi-composer textarea').fill('One more fictional question.');
  await page.locator('.fi-send').click();
  await page.waitForSelector('[data-action="approve"]');
  const defaultSend = await page.evaluate(() => preview.calls.find((row) => row.method === 'send_message'));
  assert.ok(!('model' in defaultSend.args), 'the provider default sends no model key');
  await page.goto(base + '/?scene=empty'); await waitApp();
  await page.locator('[data-action="new"]').click();
  await page.locator('[data-picker-btn="provider"]').click();
  await page.locator('[data-picker="provider"] [data-picker-option]').nth(1).click();
  await page.locator('[data-picker-btn="model"]').click();
  assert.equal(await page.locator('[data-picker="model"] [data-picker-option]').count(), 9, 'long catalog listed');
  const modelSearch = page.locator('[data-picker-search="model"]');
  assert.equal(await modelSearch.count(), 1, 'long catalogs get a search box');
  await modelSearch.fill('mini');
  assert.equal(await page.locator('[data-picker="model"] [data-picker-option]').count(), 4, 'search filters the catalog');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('[data-picker-menu="model"]').isVisible(), false, 'Escape closes the menu');
  await page.goto(base + '/?scene=busy'); await page.waitForSelector('.fi-tool-group');
  await page.evaluate(() => { const thread = document.querySelector('.fi-thread'); thread.scrollTop = thread.scrollHeight / 2; });
  assert.equal(await page.evaluate(() => document.scrollingElement.scrollTop), 0, 'the page itself never scrolls');
  assert.equal(await page.evaluate(() => { const host = document.querySelector('#page'); return host.scrollHeight > host.clientHeight + 1; }), false, 'the app fits its host without overflow');
  await page.goto(base + '/?scene=context'); await page.waitForSelector('.fi-drawer-shell:not([hidden]) .fi-context-chip');
  assert.ok((await page.locator('.fi-context-chip').textContent()).includes('Northstar Components')); await screenshot('contextual-drawer');
  await page.locator('[data-action="remove-context"]').click(); await page.locator('.fi-composer textarea').fill('Review the permitted records.'); await page.locator('.fi-send').click();
  await page.waitForSelector('[data-action="approve"]');
  const submission = await page.evaluate(() => preview.calls.find((row) => row.method === 'send_message'));
  assert.equal(submission.args.context, null); assert.ok(!JSON.stringify(submission.args).includes('Commercial'));
  await page.locator('[data-action="approve"]').click(); await page.locator('[data-action="close"]').click();
  /* the pill no longer carries a notification dot; a finished background run is seen on reopen */
  await page.waitForFunction(() => Object.values(preview.snapshots).some((row) => row.run && row.run.state === 'completed'), { timeout: 12000 });
  await page.locator('.fi-global-toggle').click(); await page.waitForFunction(() => document.querySelector('[data-slot="messages"]').textContent.includes('Review complete')); /* the answer in the thread is the outcome; no Completed chip */
  await page.evaluate(() => { preview.offline = true; preview.emit({ conversation: Object.keys(preview.snapshots).at(-1) }); });
  await page.waitForFunction(() => document.querySelector('[data-slot="banner"]').textContent.includes('Reconnecting'));
  await page.evaluate(() => { preview.offline = false; dispatchEvent(new Event('online')); });
  await page.waitForFunction(() => !document.querySelector('[data-slot="banner"]').textContent.includes('Reconnecting'));
  await page.locator('[data-action="close"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + '/?scene=empty'); await waitApp(); await screenshot('workspace-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.locator('[data-action="sidebar"]').count(), 0, 'the custom sidebar toggle is gone');
  assert.equal(await page.locator('[data-input="search"]').count(), 0, 'the custom sidebar search is gone');
  assert.equal(await page.locator('[data-action="menu"]').count(), 0, 'the header menu is gone');
  await page.evaluate(() => frappe.set_route('intelligence', 'chat-1')); /* a Desk list row lands on this same route */
  await page.waitForFunction(() => document.querySelector('[data-slot="title"]').textContent.trim() === 'Review outstanding sales orders');
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="approve"]'); await page.locator('.fi-approval').scrollIntoViewIfNeeded(); await screenshot('approval-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto(base + '/?scene=busy'); await page.waitForSelector('.fi-tool-group');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.evaluate(() => { const host = document.querySelector('#page'); return host.scrollHeight > host.clientHeight + 1; }), false, 'no whole-page scroll on mobile');
  await screenshot('tool-group-mobile');
  await page.goto(base + '/?scene=context'); await page.waitForSelector('.fi-context-chip');
  assert.ok(await page.evaluate(() => Math.abs(document.querySelector('.fi-drawer-app').getBoundingClientRect().height - document.querySelector('.fi-drawer-shell').getBoundingClientRect().height) <= 2), 'Mobile drawer fills its viewport-height shell');
  await screenshot('drawer-mobile');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.fi-drawer-shell').isVisible(), false);
  assert.deepEqual(errors, []); assert.deepEqual(outbound, []);
  console.log('Browser flows passed: workspace, tool group collapse, scroll-to-bottom, model picker, scoped and grouped approvals, auto-approved rows, no header menu, native navigation, approve/deny, rename/archive, drawer context, background completion, reconnect, keyboard/mobile.');
  console.log('Screenshots saved to ' + output + '. Fixture host only; no live Frappe or provider validation.');
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); server.kill('SIGTERM'); });
