/* Optional real-browser suite. Requires approved local Playwright tooling and a Chromium installation.
 * All application APIs are explicit in-memory fixtures; this does not certify live Frappe/provider behavior.
 */
'use strict';
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '../..');
const output = path.join(root, 'dev/screenshots');
const port = Number(process.env.PREVIEW_PORT || 8791);
const base = 'http://127.0.0.1:' + port;
const server = spawn(process.execPath, [path.join(root, 'dev/preview-server.cjs')], { env: { ...process.env, PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
const ready = new Promise((resolve, reject) => { server.stdout.on('data', (chunk) => { if (String(chunk).includes('Mock Intelligence preview:')) resolve(); }); server.on('error', reject); server.on('exit', (code) => { if (code) reject(new Error('Preview server failed: ' + code)); }); });
let browser;
(async () => {
  await ready; fs.mkdirSync(output, { recursive: true });
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1040 }, deviceScaleFactor: 1, reducedMotion: 'reduce' });
  const page = await context.newPage(), errors = [], outbound = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.route('**/*', async (route) => { if (!route.request().url().startsWith(base)) { outbound.push(route.request().url()); await route.abort(); } else await route.continue(); });
  const screenshot = (name) => page.screenshot({ path: path.join(output, name + '.png'), fullPage: true });
  const waitApp = async () => { await page.waitForSelector('.fi-welcome'); await page.waitForFunction(() => !document.querySelector('.fi-app').getAttribute('aria-busy') || document.querySelector('.fi-app').getAttribute('aria-busy') === 'false'); };
  await page.goto(base + '/?scene=empty'); await waitApp();
  assert.equal(await page.locator('.fi-conversation').count(), 4); await screenshot('workspace-empty-desktop');
  await page.locator('[data-action="settings"]').click();
  await page.locator('.fi-provider-form input[name="title"]').fill('Preview custom provider');
  await page.locator('.fi-provider-form select[name="kind"]').selectOption('Custom');
  await page.locator('.fi-provider-form input[name="model"]').fill('configured-model');
  await page.locator('.fi-provider-form input[name="base_url"]').fill('https://api.example.test/v1');
  await page.locator('.fi-provider-form input[name="api_key"]').fill('fixture-not-a-real-key');
  await screenshot('provider-editor');
  await page.locator('.fi-provider-form button[type="submit"]').click();
  await page.waitForSelector('.fi-modal-overlay', { state: 'detached' });
  assert.equal(await page.evaluate(() => preview.calls.filter((row) => row.method === 'save_provider').length), 1);
  await page.locator('[data-action="memory"]').click(); await page.waitForSelector('.fi-memory-item');
  await page.locator('.fi-memory-form textarea').fill('Prefer concise summaries with record links.');
  await page.locator('.fi-memory-form button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelectorAll('.fi-memory-item').length === 2); await screenshot('memory-editor');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.fi-modal-overlay').count(), 0);
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="approve"]');
  await page.locator('.fi-approval').scrollIntoViewIfNeeded(); await screenshot('workspace-approval-desktop');
  await page.locator('#theme-toggle').click(); await screenshot('workspace-approval-dark');
  await page.locator('[data-action="approve"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="run"]').textContent.includes('Completed'));
  assert.equal(await page.evaluate(() => preview.calls.filter((row) => row.method === 'approve').length), 1);
  await page.locator('[data-action="rename"]').click(); await page.locator('.fi-modal input[name="title"]').fill('Reviewed open orders'); await page.locator('.fi-modal button[type="submit"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="title"]').textContent === 'Reviewed open orders');
  await page.locator('[data-action="archive"]').click(); await page.locator('[data-action="confirm-archive"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="subtitle"]').textContent.includes('Archived'));
  assert.equal(await page.locator('.fi-composer textarea').isDisabled(), true);
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="deny"]'); await page.locator('[data-action="deny"]').click();
  await page.waitForFunction(() => document.querySelector('[data-slot="run"]').textContent.includes('Completed'));
  assert.equal(await page.evaluate(() => preview.calls.find((row) => row.method === 'approve').args.decision), 'deny');
  await page.goto(base + '/?scene=context'); await page.waitForSelector('.fi-drawer-shell:not([hidden]) .fi-context-chip');
  assert.ok((await page.locator('.fi-context-chip').textContent()).includes('Northstar Components')); await screenshot('contextual-drawer');
  await page.locator('[data-action="remove-context"]').click(); await page.locator('.fi-composer textarea').fill('Review the permitted records.'); await page.locator('.fi-send').click();
  await page.waitForSelector('[data-action="approve"]');
  const submission = await page.evaluate(() => preview.calls.find((row) => row.method === 'send_message'));
  assert.equal(submission.args.context, null); assert.ok(!JSON.stringify(submission.args).includes('Commercial'));
  await page.locator('[data-action="approve"]').click(); await page.locator('[data-action="close"]').click();
  await page.waitForSelector('.fi-global-toggle.has-update', { timeout: 12000 });
  await page.locator('.fi-global-toggle').click(); await page.waitForFunction(() => document.querySelector('[data-slot="run"]').textContent.includes('Completed'));
  await page.evaluate(() => { preview.offline = true; preview.emit({ conversation: Object.keys(preview.snapshots).at(-1) }); });
  await page.waitForFunction(() => document.querySelector('[data-slot="banner"]').textContent.includes('Reconnecting'));
  await page.evaluate(() => { preview.offline = false; dispatchEvent(new Event('online')); });
  await page.waitForFunction(() => !document.querySelector('[data-slot="banner"]').textContent.includes('Reconnecting'));
  await page.locator('[data-action="close"]').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + '/?scene=empty'); await waitApp(); await screenshot('workspace-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.locator('[data-action="sidebar"]').click(); assert.equal(await page.locator('.fi-sidebar').isVisible(), true);
  await page.locator('[data-input="search"]').fill('month-end'); await page.waitForFunction(() => document.querySelectorAll('.fi-conversation').length === 1);
  await page.locator('.fi-conversation').click(); await page.waitForFunction(() => document.querySelector('[data-slot="title"]').textContent.includes('month-end'));
  await page.goto(base + '/?scene=approval'); await page.waitForSelector('[data-action="approve"]'); await page.locator('.fi-approval').scrollIntoViewIfNeeded(); await screenshot('approval-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto(base + '/?scene=context'); await page.waitForSelector('.fi-context-chip');
  assert.ok(await page.evaluate(() => Math.abs(document.querySelector('.fi-drawer-app').getBoundingClientRect().height - document.querySelector('.fi-drawer-shell').getBoundingClientRect().height) <= 2), 'Mobile drawer fills its viewport-height shell');
  await screenshot('drawer-mobile');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.fi-drawer-shell').isVisible(), false);
  assert.deepEqual(errors, []); assert.deepEqual(outbound, []);
  console.log('Browser flows passed: workspace, provider save, scoped memory, approve/deny, rename/archive, drawer context, background completion, reconnect, keyboard/mobile.');
  console.log('Screenshots saved to ' + output + '. Fixture host only; no live Frappe or provider validation.');
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); server.kill('SIGTERM'); });
